# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">=1.4.0"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#  config.vm.box_url = "NOT_UPLOADED_ANYWHERE"

  config.vm.box = "centos-6.5-64-jboss"
  config.vm.box_url = "NONE" 
#  config.vm.network :forwarded_port, guest: 9990, host: 9990
#  config.vm.network :forwarded_port, guest: 9999, host: 9999
#  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :private_network, ip: "10.10.3.11"  # sy1
  config.vm.network :private_network, ip: "10.10.3.21"  # rtgov1 
  config.vm.network :private_network, ip: "10.10.3.31"  # dtgov1
  config.vm.network :private_network, ip: "10.10.3.41"  # sramp1
  config.vm.network :private_network, ip: "10.10.3.51"  # db1
  # config.vm.network :public_network
  config.ssh.username = "jboss"
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  config.vm.synced_folder "/home/jorge/jboss/software/", "/jboss_software"
 
  config.vm.provider :virtualbox do |vb|
     # vb.gui = true
     vb.customize ["modifyvm", :id, "--name", "jboss-fsw-demo", "--memory", "6144"]
  end

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file base.pp in the manifests_path directory.
  #
  # An example Puppet manifest to provision the message of the day:
  #
  # # group { "puppet":
  # #   ensure => "present",
  # # }
  # #
  # # File { owner => 0, group => 0, mode => 0644 }
  # #
  # # file { '/etc/motd':
  # #   content => "Welcome to your Vagrant-built virtual machine!
  # #               Managed by Puppet.\n"
  # # }
  #
  config.vm.provision :puppet do |puppet|
     puppet.manifests_path = "manifests"
     puppet.manifest_file  = "site.pp"
  end

end
