# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">=1.6.2"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

   config.vm.box = "jmorales/centos65-jboss"
   config.ssh.username = "jboss"
   config.ssh.forward_agent = true
   config.ssh.forward_x11 = true

   config.vm.define "sy1", primary: true do |node1|
      node1.vm.network :private_network, ip: "10.15.1.10" #, virtualbox__intnet: "mynetwork" # SERVICE
      node1.vm.network :private_network, ip: "10.0.2.11" #, virtualbox__intnet: "management"  # MGMT
      node1.vm.network :private_network, ip: "10.0.1.11" , virtualbox__intnet: "internalnetwork" # REPLICATION
      # Public network should be configured to be able to access YUM repos to install things
      #  node1.vm.network :public_network
      
      node1.vm.provider :virtualbox do |vb|
         # vb.gui = true
         vb.customize ["modifyvm", :id, "--name", "sy-node1", "--memory", "4096"]
      end
   
      node1.vm.provision :shell do |shell|
         shell.inline = "/vagrant/manifests/setup-pre_req.sh $*"
         shell.args = [#"-s", "jboss:jboss",
                       "-H", "sy1",
                       "-h", "sy1:10.15.1.10", 
                       "-h", "sy2:10.15.1.11", 
                       "-h", "sy1-repl:10.0.1.11",
                       "-h", "sy2-repl:10.0.1.12",
                       "-h", "sy1-mgmt:10.0.2.11",
                       "-h", "sy2-mgmt:10.0.2.11",
                       "-h", "sy-db:10.0.1.13",
                       "-h", "sy-ad:10.0.1.13",
                       "-j", "jdk-7u55-linux-x64.tar.gz",
                       "-d", "/opt",
                       "-l", "9216"]
      end

      node1.vm.provision :shell do |shell|
         shell.inline = "/vagrant/manifests/setup-switchyard.sh $*"
         shell.args = ["-i", "switchyard", "-P", "standalone-full-ha.xml", "-b", "sy1", "-m", "sy1-mgmt", "-U", "jboss:jboss", "-u", "admin", "-p", "admin123!", "-d", "/opt"]
      end

   end
   
   config.vm.define "sy2" do |node2|
      node1.vm.network :private_network, ip: "10.15.1.11" #, virtualbox__intnet: "mynetwork" # SERVICE
      node1.vm.network :private_network, ip: "10.0.2.12" #, virtualbox__intnet: "management"  # MGMT
      node1.vm.network :private_network, ip: "10.0.1.12" , virtualbox__intnet: "internalnetwork" # REPLICATION
      # Public network should be configured to be able to access YUM repos to install things
      #  node2.vm.network :public_network

      node2.vm.provider :virtualbox do |vb|
         # vb.gui = true
         vb.customize ["modifyvm", :id, "--name", "sy-node2", "--memory", "4096"]
      end
   
      node2.vm.provision :shell do |shell|
         shell.inline = "/vagrant/manifests/setup-pre_req.sh $*"
         shell.args = [#"-s", "jboss:jboss",
                       "-H", "sy2",
                       "-h", "sy1:10.15.1.10", 
                       "-h", "sy2:10.15.1.11", 
                       "-h", "sy1-repl:10.0.1.11",
                       "-h", "sy2-repl:10.0.1.12",
                       "-h", "sy1-mgmt:10.0.2.11",
                       "-h", "sy2-mgmt:10.0.2.11",
                       "-h", "sy-db:10.0.1.13",
                       "-h", "sy-ad:10.0.1.13",
                       "-j", "jdk-7u55-linux-x64.tar.gz",
                       "-d", "/opt",
                       "-l", "9216"]
      end

      node2.vm.provision :shell do |shell|
         shell.inline = "/vagrant/manifests/setup-switchyard.sh $*"
         shell.args = ["-i", "switchyard", "-P", "standalone-full-ha.xml", "-b", "sy2", "-m", "sy2-mgmt", "-U", "jboss:jboss", "-u", "admin", "-p", "admin123!", "-d", "/opt"]
      end
      
   end

end
