# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">=1.6.2"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

   config.vm.box = "jmorales/centos65-jboss"
   config.ssh.username = "jboss"
   config.ssh.forward_agent = true
   config.ssh.forward_x11 = true

   config.vm.define "switchyard1", primary: true do |node1|
      node1.vm.network :private_network, ip: "10.15.1.10" #, virtualbox__intnet: "mynetwork"
      node1.vm.network :private_network, ip: "10.0.2.11" , virtualbox__intnet: "management"
      node1.vm.network :private_network, ip: "10.0.1.11", virtualbox__intnet: "internalnetwork"
      # Public network should be configured to be able to access YUM repos to install things
      #  node1.vm.network :public_network
      
      node1.vm.provider :virtualbox do |vb|
         # vb.gui = true
         vb.customize ["modifyvm", :id, "--name", "switchyard-node1", "--memory", "4096"]
      end
   
      node1.vm.provision :shell do |shell|
         shell.inline = "/vagrant/manifests/setup-pre_req.sh $*"
         shell.args = ["-u", "jboss",
                       "-H", "switchyard1",
                       "-h", "switchyard1:10.15.1.10", 
                       "-h", "switchyard2:10.15.1.11", 
                       "-h", "switchyard1-repl:10.0.1.11",
                       "-h", "switchyard2-repl:10.0.1.12",
                       "-h", "switchyard1-mgmt:10.0.2.11",
                       "-h", "switchyard2-mgmt:10.0.2.12",
                       "-h", "db1:10.0.1.13",
                       "-h", "db2:10.0.1.13",
                       "-h", "ldap:10.0.1.13",
                       "-j", "jdk-7u55-linux-x64.tar.gz",
                       "-d", "/opt"]
      end

      node1.vm.provision :shell do |shell|
         shell.inline = "/vagrant/manifests/setup-switchyard.sh $*"
         shell.args = ["-i", "fsw", "-b", "0.0.0.0", "-U", "jboss", "-u", "admin", "-p", "admin123!", "-d", "/opt"]
      end

   end
   
   config.vm.define "switchyard2" do |node2|
      node2.vm.network :private_network, ip: "10.15.1.11" #, virtualbox__intnet: "mynetwork"
      node2.vm.network :private_network, ip: "10.0.2.12" , virtualbox__intnet: "management"
      node2.vm.network :private_network, ip: "10.0.1.12", virtualbox__intnet: "internalnetwork"
      # Public network should be configured to be able to access YUM repos to install things
      #  node2.vm.network :public_network

      node2.vm.provider :virtualbox do |vb|
         # vb.gui = true
         vb.customize ["modifyvm", :id, "--name", "switchyard-node2", "--memory", "4096"]
      end
   
      node2.vm.provision :shell do |shell|
         shell.inline = "/vagrant/manifests/setup-pre_req.sh $*"
         shell.args = ["-u", "jboss",
                       "-H", "switchyard2",
                       "-h", "switchyard1:10.15.1.10", 
                       "-h", "switchyard2:10.15.1.11", 
                       "-h", "switchyard1-repl:10.0.1.11",
                       "-h", "switchyard2-repl:10.0.1.12",
                       "-h", "switchyard1-mgmt:10.0.2.11",
                       "-h", "switchyard2-mgmt:10.0.2.12",
                       "-h", "db1:10.0.1.13",
                       "-h", "db2:10.0.1.13",
                       "-h", "ldap:10.0.1.13",
                       "-j", "jdk-7u55-linux-x64.tar.gz",
                       "-d", "/opt"]
      end

      node2.vm.provision :shell do |shell|
         shell.inline = "/vagrant/manifests/setup-switchyard.sh $*"
         shell.args = ["-i", "fsw", "-b", "0.0.0.0", "-U", "jboss", "-u", "admin", "-p", "admin123!", "-d", "/opt"]
      end
      
   end
   

end
